### ISSUE TITLE
 MountVolume.SetUp failed for volume "mongo-data-mongodb-0"

### ISSUE THREAD

**Issue by asubashi** [redhat-cop/pbl-rocketchat#4]
during deployment of rocketchat, i am facing generation of below error for MONGODB POD :

Events:
  Type     Reason       Age   From                              Message
  ----     ------       ----  ----                              -------
  Normal   Scheduled    17s   default-scheduler                 Successfully assigned rocketchat/mongodb-0 to <prefix>NODE1.<domain>
  Warning  FailedMount  16s   kubelet, <prefix>NODE1.<domain>  MountVolume.SetUp failed for volume "mongo-data-mongodb-0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/origin/openshift.local.volumes/pods/2a0cb953-a4b8-11ea-99a1-005056a7f2a6/volumes/kubernetes.io~nfs/mongo-data-mongodb-0 --scope -- mount -t nfs <prefix>master1fe.<domain>:/exports/mongo-db /var/lib/origin/openshift.local.volumes/pods/2a0cb953-a4b8-11ea-99a1-005056a7f2a6/volumes/kubernetes.io~nfs/mongo-data-mongodb-0
Output: Running scope as unit run-92782.scope.
mount.nfs: Protocol not supported
  Warning  FailedMount  16s  kubelet, <prefix>NODE1.<domain>  MountVolume.SetUp failed for volume "mongo-data-mongodb-0" : mount failed: exit status 32

Please what do you suggested to fix the issue ?

**Comment by garethahealy** [comment]
archiving
